### ISSUE TITLE
Set up dev environment

### ISSUE THREAD

**Issue by willnotwish** [willnotwish/at-the-races#1]
Per my normal procedure, I use containers. Use docker for now, although I may try podman.

### Tasks
- [x] Get ruby 2.5.8 running
- [x] Generate a Rails 4.2 app
- [x] Make sure it can connect to a mySQL 5.5 database

**Comment by willnotwish** [comment]
I used an old Dockerfile.

```
nick@nick-pc:~/dev/at-the-races$ docker run --rm -it -u nick willnotwish/at-the-races-dev:2.5.8 bash
nick@f8811737fda9:/app$ whoami
nick
nick@f8811737fda9:/app$ uname
Linux
nick@f8811737fda9:/app$ ruby -v
ruby 2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux]
```

**Comment by willnotwish** [comment]
After some manual messing with `Gemfile`, I think I have a working Rails 4.2.10 app.

I'm going to strip out some of the "noise", though. Also need to add mysql support, so I need mysql headers in the Docker image.

No, I don't. I added the wrong gem. I needed `mysql2`. You'd think I'd know that by now.

Some messing about with `mysql2` version to get bundle to bundle properly. I settled on `gem 'mysql2', '0.4.10'`

**Comment by willnotwish** [comment]
Now to bring up mysql 5.5 in another container.

**Comment by willnotwish** [comment]
I got it going (I think) eventually.

Try creating a dummy class `Thing` at the rails console.

Seems to work OK:

```
nick@nick-pc:~/dev/at-the-races$ dc exec one bundle exec rails c
Loading development environment (Rails 4.2.10)
irb(main):001:0> Thing
=> Thing (call 'Thing.connection' to establish a connection)
irb(main):002:0> Thing.create name: 'foo'
   (0.1ms)  BEGIN
  SQL (0.1ms)  INSERT INTO `things` (`name`, `created_at`, `updated_at`) VALUES ('foo', '2024-10-25 11:07:48', '2024-10-25 11:07:48')
   (1.8ms)  COMMIT
=> #<Thing id: 1, name: "foo", created_at: "2024-10-25 11:07:48", updated_at: "2024-10-25 11:07:48">

```

**Comment by willnotwish** [comment]
Closing this now as complete.
